# Permalinks
permalink:           pretty

# Setup
title:               John Tan
tagline:             A Copied Data Science Blog
url:                 http://Cytan2411.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              John Tan
  url:               https://twitter.com/zaglamir
  email:             zach@thisismetis.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/cytan2411

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
